### ISSUE TITLE
Do you use name `global_addressbooks` or `global_addressbook` (without 's') in PGSQL backend?

### ISSUE THREAD

**Issue by ghost** [t3chguy/Roundcube-SQL-Global-Address-Books#10]
During my testing, it queries `global_addressbooks` instead of `global_addressbook` (the name in MySQL VIEW). could you help check this?

**Comment by t3chguy** [comment]
Going through the code, there are no calls to `...book(s)` and the code has 0 knowledge of whether you are running MySQL or PgSQL, Roundcube handles that transition. I see a Pull Request which I'll check out in a second.
