### ISSUE TITLE
Any plan to release a stable release? Let's start promote it.

### ISSUE THREAD

**Issue by ghost** [t3chguy/Roundcube-SQL-Global-Address-Books#3]
Dear @t3chguy,

I know it's now working as expected :+1: , but still wonder, do you have any plan to release a stable release?
About "stable", i mean:
- steady configuration parameter names
- functions are all working as expected
- no big refactor requirement in near future

Also, any plan to rename your plugin name? Neither "Roundcube-SQL-Multi-Contacts" nor "wdgrc_sql_contacts " is clear, they don't even relate to "address book".

How about rename it to `sql_address_book`? Just a suggestion, it's all up to you.

I'm willing to help promote this plugin in iRedMail forum, mailing list.

**Comment by t3chguy** [comment]
I do need to pick a better name for it, internally roundcube calls them both address books and contacts, so not sure about changing the name but definitely class, folder, filenames, and config prefixes to something that won't ever change. Maybe change the name to roundcube sql multi address book? I have tested everything as much as I could on my own so just a tidy up to go.

**Comment by ghost** [comment]
It's a roundcube plugin, we don't need to mention "roundcube" in plugin name (but it's necessary in your github repository name).

Personally, i prefer `sql_address_book`: short, clear.

**Comment by t3chguy** [comment]
I think that it's a little vague, since roundcube ships with an sql address book, I'll have a little think tonight and finalise it later

**Comment by t3chguy** [comment]
Okay, I am thinking more along the lines of `sql_global_addressbooks`
since all of the books are Global to some scope, and then it'll match the MySQL View name of `global_addressbook`

**Comment by t3chguy** [comment]
@zhanghuangbin anything else you think I need to do for it to be considered stable?

**Comment by ghost** [comment]
I'm fine will this name. :)
