### ISSUE TITLE
Add some screenshot images on github project page

### ISSUE THREAD

**Issue by ghost** [t3chguy/Roundcube-SQL-Global-Address-Books#7]
Hi Michael,

Could you please add some screenshot images on github project page? so that others can see the ui and how it looks like.

Screenshot should be displayed when user visits this URL:
https://github.com/t3chguy/Roundcube-SQL-Global-Address-Books

**Comment by t3chguy** [comment]
Yeah, sure I'll do that when I get home tonight, thanks for the idea!

**Comment by t3chguy** [comment]
I just got home to find that you had beaten me to it, thank you very much, could you list what screenshots you need for an Android EAS Tutorial and I'll do those in a few hours for you

**Comment by ghost** [comment]
Sent you testing account to setup Android EAS. :)
